config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "static_pages#home"
  resources :books
  resources :users do
    resources :requests, only: [:index, :new, :create, :destroy]
    resources :relationships, only: [:index]
  end
  resources :likes, only: [:create, :edit]
  namespace :admin do
    root "books#index"
    resources :books
    resources :requests, only: [:index, :update]
    resources :publishers
    resources :authors
    resources :languages
    resources :categories
  end
  resources :user_books
  resources :comments
  resources :relationships, only: [:create, :destroy]
end

app/models/book.rb
class Book < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  belongs_to :author
  belongs_to :category
  belongs_to :publisher
  belongs_to :language
  has_many :user_books, dependent: :destroy
  has_many :requests, dependent: :destroy
  validates :author, presence: true
  validates :category, presence: true
  validates :publisher, presence: true
  validates :language, presence: true
  validates :title, presence: true, length: {minimum: 10, maximum: 100}
  validates :description, presence: true, length: {minimum: 10}
  validates :publish_date, presence: true
  mount_uploader :cover_image_name, BookUploader

  default_scope {order created_at: :desc}

  scope :of_category, -> category_id do
    where category_id: category_id if category_id.present?
  end
  scope :of_author, -> author_id do
    where author_id: author_id if author_id.present?
  end
  scope :of_publisher, -> publisher_id do
    where publisher_id: publisher_id if publisher_id.present?
  end
  scope :of_language, -> language_id do
    where language_id: language_id if language_id.present?
  end

  def is_favorite_of_user? user
    user.user_books.favorited&.map(&:book_id)&.include? id
  end

  def is_reading_of_user? user
    if user.user_books.find_by(book_id: id).nil?
      false
    else
      user.user_books.by_book_id(id).status == Settings.user_book_status.reading
    end

  end

  def is_read_of_user? user
    if user.user_books.find_by(book_id: id).nil?
      false
    else
      user.user_books.by_book_id(id).status == Settings.user_book_status.read
    end

  end

  def next_status_of_user user, target_status
    if user.user_books.find_by(book_id: id).nil?
      source_status = nil
    else
      source_status = user.user_books.by_book_id(id).status
    end
    if source_status == target_status
      Settings.user_book_status.no_status
    else
      target_status
    end
  end

  private

  def should_generate_new_friendly_id?
    slug.blank? || title_changed?
  end
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  load_and_authorize_resource
  load_and_authorize_resource find_by: :slug

  before_action :authenticate_user!
  before_action :verify_admin
  before_action :load_books_association, only: [:new, :edit]

  def index
    @search = Book.ransack params[:q]
    @search.sorts = Settings.default_sort if @search.sorts.empty?
    @books = @search.result
      .joins(:category, :author, :publisher, :language)
      .page(params[:page]).per(Settings.per_page)
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      redirect_to root_path
    else
      load_books_association
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:success] = I18n.t "admin.books.edit.success"
      redirect_to admin_root_path
    else
      flash[:danger] = I18n.t "admin.books.edit.failed"
      render :edit
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = I18n.t "admin.books.destroy.success"
    else
      flash[:danger] = I18n.t "admin.books.destroy.failed"
    end
    redirect_to admin_books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :cover_image_name,
      :number_of_pages, :description, :publish_date, :price,
      :author_id, :category_id, :publisher_id, :language_id, :is_in_library )
  end

  def load_books_association
    @authors = Author.all
    @categories = Category.all
    @publishers = Publisher.all
    @languages = Language.all
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  load_and_authorize_resource find_by: :slug

  before_action :authenticate_user!
  before_action :load_book, only: :show

  def index
    params[:books_filter] ||= Settings.books_filter[:category]
    @search = Book.send(params[:books_filter], params[params[:books_filter]])
      .ransack(params[:q])
    @books = @search.result
      .joins(:category, :author, :publisher, :language)
      .page(params[:page]).per(Settings.per_page)
    @categories = Category.all
    @authors = Author.all
    @languages = Language.all
    @publishers = Publisher.all
  end

  def show
    unless @book
      flash[:danger] = t "books.book_infomation.not_found"
      redirect_to books_path
    end
  end

  private

  def load_book
    if @book.nil?
      flash[:danger] = t "books.book_infomation.not_found"
      redirect_to root_url
    end
  end
end
11

app/views/admin/books/_form.html.erb
<% unless @book.cover_image_name.url.nil? %>
  <div class="col-lg-12 text-center padding-top-50">
    <%= image_tag @book.cover_image_name.url, class: "book-cover-image-size" %>
  </div>
<% end %>
<%= form_for(@book, html: {multipart: true},
  url: path) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="col-lg-12 padding-0 margin-top-100">
    <div class="col-lg-3">
      <%= f.label :category_id, t("admin.books.new.categories") %>
      <%= f.select(:category_id,
        options_from_collection_for_select(@categories, :id, :name,
          @book.category_id), {},class: "form-control") %>
    </div>
    <div class="col-lg-3">
      <%= f.label :author_id, t("admin.books.new.authors") %>
      <%= f.select(:author_id,
        options_from_collection_for_select(@authors, :id, :name,
          @book.author_id), {}, class: "form-control") %>
    </div>
    <div class="col-lg-3">
      <%= f.label :language_id, t("admin.books.new.languages") %>
      <%= f.select(:language_id,
        options_from_collection_for_select(@languages, :id, :name,
          @book.language_id), {}, class: "form-control") %>
    </div>
    <div class="col-lg-3">
      <%= f.label :publisher_id, t("admin.books.new.publishers") %>
      <%= f.select(:publisher_id,
        options_from_collection_for_select(@publishers, :id, :name,
        @book.publisher_id), {}, class: "form-control") %>
    </div>
  </div>
  <div class="col-lg-12 padding-0 padding-top-20">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="col-lg-12 padding-0 padding-top-20">
    <div class="col-lg-6">
      <%= f.label :number_of_pages %>
      <%= f.text_field :number_of_pages, class: "form-control" %>
    </div>
    <div class="col-lg-6">
      <%= f.label :cover_image_name %>
      <%= f.file_field :cover_image_name,
        accept: "image/jpeg, image/gif, image/png, image/jpg" %>
    </div>
  </div>
  <div class="col-lg-12 padding-0 padding-top-20">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10, class: "form-control" %>
  </div>
  <div class="col-lg-12 padding-0 padding-top-20">
    <div class="col-lg-6">
      <%= f.label :price %>
      <%= f.text_field :price, class: "form-control" %>
    </div>
    <div class="col-lg-6">
      <%= f.label :publish_date %>
      <div class="input-group date form_date col-lg-12">
         <%= f.text_field :publish_date, class: "form-control" %>
         <span class="input-group-addon">
           <span class="glyphicon glyphicon-calendar"></span>
         </span>
      </div>
    </div>
  </div>
  <div class="col-lg-12 padding-0 padding-top-20">
    <%= f.label :is_in_library %>
    <%= f.check_box :is_in_library, class: "" %>
  </div>
  <div class="col-lg-12 padding-0 padding-top-20 text-center">
    <%= f.submit t("admin.books.new.submit"),
      class: "btn btn-primary padding-20 box-shadow" %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<%= provide :title, t("admin.books.new.title") %>
<div id="books">
  <div class="row">
    <div class="col-lg-offset-1 col-lg-10 padding-top-50">
      <div class="col-lg-12">
        <h1 class="text-center title-function">
          <%= t "admin.books.edit.title" %>
        </h1>
      </div>
      <%= render "form", path: admin_book_path(@book) %>
    </div>
  </div>
</div>

app/views/admin/books/index.html.erb
<%= provide :title, t("admin.books.index.title") %>
<div id="books">
  <div class="row padding-top-50">
    <div class="col-lg-12">
      <%= link_to new_admin_book_path do %>
        <%= button_tag t("admin.books.index.btn_add_book"),
          class: "btn btn-primary box-shadow" %>
      <% end %>
    </div>
  </div>
  <div class="row padding-top-50">
    <div class="col-lg-12 book-form-search">
      <%= search_form_for @search, url: admin_books_path do |f| %>
        <%= f.condition_fields do |condition| %>
          <div class="col-lg-3">
            <%= condition.attribute_fields do |attribute| %>
              <%= attribute.attribute_select associations: [:category,
                :author, :publisher, :language] %>
            <% end %>
          </div>
          <div class="col-lg-3">
            <%= condition.predicate_select %>
          </div>
          <div class="col-lg-3">
            <%= condition.value_fields do |value| %>
              <%= value.text_field :value %>
            <% end %>
          </div>
        <% end %>
        <div class="col-lg-3">
          <%= f.submit t("admin.search"),
            class: "btn btn-default books-btn-search" %>
        </div>
        <div class="col-lg-12 padding-0">
          <div class="col-lg-5 padding-0">
            <%= f.sort_fields do |sort| %>
              <%= sort.sort_select %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row padding-top-50">
    <div class="col-lg-12">
      <table class="table table-bordered book-table">
        <thead>
          <tr>
            <th class="width-5"><%= t "admin.books.index.numbers" %></th>
            <th class="width-10"><%= t "admin.books.index.cover_image" %></th>
            <th class="width-10"><%= t "admin.books.index.title" %></th>
            <th class="width-10"><%= t "books.menu_left.author" %></th>
            <th class="width-10"><%= t "books.menu_left.category" %></th>
            <th class="width-10"><%= t "books.menu_left.language" %></th>
            <th class="width-10"><%= t "books.menu_left.publisher" %></th>
            <th class="width-10">
              <%= t "admin.books.index.is_in_library" %>
            </th>
            <th class="width-10"><%= t "admin.books.index.created_at" %></th>
            <th class="width-10"><%= t "admin.books.index.edit" %></th>
            <th class="width-10"><%= t "admin.books.index.delete" %></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each_with_index do |book, index| %>
            <tr>
              <td><%= increase_one index %></td>
              <td><%= image_tag book.cover_image_name.url,
                class: "resize_image" %></td>
              <td><%= book.title %></td>
              <td><%= book.author.name %></td>
              <td><%= book.category.name %></td>
              <td><%= book.language.name %></td>
              <td><%= book.publisher.name %></td>
              <td><%= check_box_tag "", "", book.is_in_library,
                disabled: true, class: "font-size-20" %></td>
              <td><%= book.created_at
                .strftime(t "datetime_format.date_and_time") %></td>
              <td>
                <%= link_to edit_admin_book_path(book),
                  class: "btn btn-info font-size-20" do %>
                  <span class="glyphicon glyphicon-edit"></span>
                <% end %>
              </td>
              <td>
                <%= link_to admin_book_path(book), method: :delete,
                  data: {confirm: t("admin.books.index.confirm_delete")},
                  class: "btn btn-danger font-size-20" do %>
                  <span class="glyphicon glyphicon-trash"></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/books/new.html.erb
<%= provide :title, t("admin.books.new.title") %>
<div id="books">
  <div class="row">
    <div class="col-lg-offset-1 col-lg-10 padding-top-50">
      <div class="col-lg-12">
        <h1 class="text-center title-function">
          <%= t "admin.books.new.title" %>
        </h1>
      </div>
      <%= form_for(@book, html: {multipart: true},
        url: admin_books_path) do |f| %>
        <%= render "shared/error_messages", object: f.object %>
        <div class="col-lg-12 padding-0 margin-top-100">
          <div class="col-lg-3">
            <%= f.label :category_id, t("admin.books.new.categories") %>
            <%= f.select(:category_id,
              options_from_collection_for_select(@categories, :id, :name),
              {}, class: "form-control") %>
          </div>
          <div class="col-lg-3">
            <%= f.label :author_id, t("admin.books.new.authors") %>
            <%= f.select(:author_id,
              options_from_collection_for_select(@authors, :id, :name),
              {}, class: "form-control") %>
          </div>
          <div class="col-lg-3">
            <%= f.label :language_id, t("admin.books.new.languages") %>
            <%= f.select(:language_id,
              options_from_collection_for_select(@languages, :id, :name), {},
              class: "form-control") %>
          </div>
          <div class="col-lg-3">
            <%= f.label :publisher_id, t("admin.books.new.publishers") %>
            <%= f.select(:publisher_id,
              options_from_collection_for_select(@publishers, :id, :name),
              {}, class: "form-control") %>
          </div>
        </div>
        <div class="col-lg-12 padding-0 padding-top-20">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="col-lg-12 padding-0 padding-top-20">
          <div class="col-lg-6">
            <%= f.label :number_of_pages %>
            <%= f.text_field :number_of_pages, class: "form-control" %>
          </div>
          <div class="col-lg-6">
            <%= f.label :cover_image_name %>
            <%= f.file_field :cover_image_name,
              accept: "image/jpeg, image/gif, image/png, image/jpg" %>
          </div>
        </div>
        <div class="col-lg-12 padding-0 padding-top-20">
          <%= f.label :description %>
          <%= f.text_area :description, rows: 10, class: "form-control" %>
        </div>
        <div class="col-lg-12 padding-0 padding-top-20">
          <div class="col-lg-6">
            <%= f.label :price %>
            <%= f.text_field :price, class: "form-control" %>
          </div>
          <div class="col-lg-6">
            <%= f.label :publish_date %>
            <div class="input-group date form_date col-lg-12">
               <%= f.text_field :publish_date, class: "form-control" %>
               <span class="input-group-addon">
                 <span class="glyphicon glyphicon-calendar"></span>
               </span>
            </div>
          </div>
        </div>
        <div class="col-lg-12 padding-0 padding-top-20">
          <%= f.label :is_in_library %>
          <%= f.check_box :is_in_library, class: "" %>
        </div>
        <div class="col-lg-12 padding-0 padding-top-20 text-center">
          <%= f.submit "Submit", class: "btn btn-primary padding-20 box-shadow" %>
        </div>
      <% end %>
    </div>
  </div>
</div>