config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "static_pages#home"
  resources :books
  resources :users do
    resources :requests, only: [:index, :new, :create, :destroy]
    resources :relationships, only: [:index]
  end
  resources :likes, only: [:create, :edit]
  namespace :admin do
    root "books#index"
    resources :books
    resources :requests, only: [:index, :update]
    resources :publishers
    resources :authors
    resources :languages
    resources :categories
  end
  resources :user_books
  resources :comments
  resources :relationships, only: [:create, :destroy]
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books, dependent: :destroy
  validates :name, presence: true, length: {maximum: 100}
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :verify_admin

  def index
    @search = Author.ransack params[:q]
    @search.sorts = Settings.default_sort if @search.sorts.empty?
    @authors = @search.result
      .page(params[:page]).per(Settings.per_page)
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new author_params
    if @author.save
      flash[:success] = I18n.t "admin.authors.new.flash.success_create"
      redirect_to admin_authors_path
    else
      flash[:error] = I18n.t "admin.authors.new.flash.error_create"
      render :new
    end
  end

  def edit
  end

  def update
    if @author.update(author_params)
      flash[:success] = I18n.t "admin.authors.edit.success"
      redirect_to admin_authors_path
    else
      flash[:danger] = I18n.t "admin.authors.edit.failed"
      render :edit
    end
  end

  def destroy
    if @author.destroy
      flash[:success] = I18n.t "admin.authors.destroy.success"
    else
      flash[:danger] = I18n.t "admin.authors.destroy.failed"
    end
    redirect_to admin_authors_path
  end

  private
  def author_params
    params.require(:author).permit :name
  end
end

app/views/admin/authors/_form.html.erb
<%= form_for [:admin, @author] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <%= f.submit t(".submit_button"), class: "btn btn-primary" %>
<% end %>

app/views/admin/authors/edit.html.erb
<%= provide :title, t(".title") %>
<div id="books">
  <div class="row">
    <div class="col-lg-offset-1 col-lg-10 padding-top-50">
      <div class="col-lg-12">
        <h1 class="text-center title-function">
          <%= t ".title" %>
        </h1>
      </div>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admin/authors/index.html.erb
<%= provide :title, t("admin.authors.index.title") %>
<div id="authors">
  <div class="row padding-top-50">
    <div class="col-lg-12">
      <%= link_to new_admin_author_path do %>
        <%= button_tag t("admin.authors.index.btn_add_author"),
          class: "btn btn-primary box-shadow" %>
      <% end %>
    </div>
  </div>
  <div class="row padding-top-50">
    <div class="col-lg-12 book-form-search">
      <%= search_form_for @search, url: admin_authors_path do |f| %>
        <%= f.condition_fields do |condition| %>
          <div class="col-lg-3">
            <%= condition.attribute_fields do |attribute| %>
                <%= attribute.attribute_select %>
            <% end %>
          </div>
          <div class="col-lg-3">
            <%= condition.predicate_select %>
          </div>
          <div class="col-lg-3">
            <%= condition.value_fields do |value| %>
                <%= value.text_field :value %>
            <% end %>
          </div>
          <% end %>
          <div class="col-lg-3">
            <%= f.submit t("admin.search"),
              class: "btn btn-default books-btn-search" %>
          </div>
          <div class="col-lg-12 padding-0">
            <div class="col-lg-5 padding-0">
              <%= f.sort_fields do |sort| %>
                <%= sort.sort_select %>
              <% end %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
  <div class="row padding-top-50">
    <div class="col-lg-12">
      <table class="table table-bordered book-table">
        <thead>
        <tr>
          <th class="width-5"><%= t ".numbers" %></th>
          <th class="width-10"><%= t ".author_name" %></th>
          <th class="width-10"><%= t ".created_at" %></th>
          <th class="width-10"><%= t ".edit" %></th>
          <th class="width-10"><%= t ".delete" %></th>
        </tr>
        </thead>
        <tbody>
        <% @authors.each_with_index do |author, index| %>
          <tr>
            <td><%= increase_one index %></td>
            <td><%= author.name %></td>
            <td><%= author.created_at
              .strftime(t "datetime_format.date_and_time") %></td>
            <td>
              <%= link_to edit_admin_author_path(author),
                class: "btn btn-info font-size-20" do %>
                  <span class="glyphicon glyphicon-edit"></span>
              <% end %>
            </td>
            <td>
              <%= link_to admin_author_path(author), method: :delete,
                data: {confirm: t(".confirm_delete")},
                class: "btn btn-danger font-size-20" do %>
                  <span class="glyphicon glyphicon-trash"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/authors/new.html.erb
<%= provide :title, t(".title") %>
<div id="books">
  <div class="row">
    <div class="col-lg-offset-1 col-lg-10 padding-top-50">
      <div class="col-lg-12">
        <h1 class="text-center title-function">
          <%= t ".title" %>
        </h1>
      </div>
      <%= render "form" %>
    </div>
  </div>
</div>