config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  root "static_pages#home"
  resources :books
  resources :users do
    resources :requests, only: [:index, :new, :create, :destroy]
    resources :relationships, only: [:index]
  end
  resources :likes, only: [:create, :edit]
  namespace :admin do
    root "books#index"
    resources :books
    resources :requests, only: [:index, :update]
    resources :publishers
    resources :authors
    resources :languages
    resources :categories
  end
  resources :user_books
  resources :comments
  resources :relationships, only: [:create, :destroy]
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books, dependent: :destroy
  validates :name, presence: true, length: {minimum:6, maximum: 100}
  validates :address, presence: true, length: {maximum: 255}
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :verify_admin

  def index
    @search = Publisher.ransack params[:q]
    @search.sorts = Settings.default_sort if @search.sorts.empty?
    @publishers = @search.result
      .page(params[:page]).per(Settings.per_page)
    @search.build_condition if @search.conditions.empty?
    @search.build_sort if @search.sorts.empty?
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new publisher_params
    if @publisher.save
      flash[:success] = I18n.t "admin.publishers.new.flash.success_create"
      redirect_to admin_publishers_path
    else
      flash[:error] = I18n.t "admin.publishers.new.flash.error_create"
      render :new
    end
  end

  def edit
  end

  def update
    if @publisher.update(publisher_params)
      flash[:success] = I18n.t "admin.publishers.edit.success"
      redirect_to admin_publishers_path
    else
      flash[:danger] = I18n.t "admin.publishers.edit.failed"
      render :edit
    end
  end

  def destroy
    if @publisher.destroy
      flash[:success] = I18n.t "admin.publishers.destroy.success"
    else
      flash[:danger] = I18n.t "admin.publishers.destroy.failed"
    end
    redirect_to admin_publishers_path
  end

  private
  def publisher_params
    params.require(:publisher).permit :name, :address, :phone_number
  end
end

app/views/admin/publishers/_form.html.erb
<%= simple_form_for [:admin, @publisher] do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/admin/publishers/index.html.erb
<%= provide :title, t("admin.publishers.index.title") %>
<div id="publishers">
  <div class="row padding-top-50">
    <div class="col-lg-12">
      <%= link_to new_admin_publisher_path do %>
        <%= button_tag t("admin.publishers.index.btn_add_publisher"),
          class: "btn btn-primary box-shadow" %>
      <% end %>
    </div>
  </div>
  <div class="row padding-top-50">
    <div class="col-lg-12 book-form-search">
      <%= search_form_for @search, url: admin_publishers_path do |f| %>
        <%= f.condition_fields do |condition| %>
          <div class="col-lg-3">
            <%= condition.attribute_fields do |attribute| %>
              <%= attribute.attribute_select %>
            <% end %>
          </div>
          <div class="col-lg-3">
            <%= condition.predicate_select %>
          </div>
          <div class="col-lg-3">
            <%= condition.value_fields do |value| %>
              <%= value.text_field :value %>
            <% end %>
          </div>
        <% end %>
        <div class="col-lg-3">
          <%= f.submit t("admin.search"),
            class: "btn btn-default books-btn-search" %>
        </div>
        <div class="col-lg-12 padding-0">
          <div class="col-lg-5 padding-0">
            <%= f.sort_fields do |sort| %>
              <%= sort.sort_select %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row padding-top-50">
    <div class="col-lg-12">
      <table class="table table-bordered book-table">
        <thead>
        <tr>
          <th class="width-5"><%= t ".numbers" %></th>
          <th class="width-10"><%= t ".publisher_name" %></th>
          <th class="width-10"><%= t ".publisher_address" %></th>
          <th class="width-10"><%= t ".publisher_phone_number" %></th>
          <th class="width-10"><%= t ".created_at" %></th>
          <th class="width-10"><%= t ".edit" %></th>
          <th class="width-10"><%= t ".delete" %></th>
        </tr>
        </thead>
        <tbody>
        <% @publishers.each_with_index do |publisher, index| %>
          <tr>
            <td><%= increase_one index %></td>
            <td><%= publisher.name %></td>
            <td><%= publisher.address %></td>
            <td><%= publisher.phone_number %></td>
            <td><%= publisher.created_at %></td>
            <td>
              <%= link_to edit_admin_publisher_path(publisher),
                class: "btn btn-info font-size-20" do %>
                <span class="glyphicon glyphicon-edit"></span>
              <% end %>
            </td>
            <td>
              <%= link_to admin_publisher_path(publisher), method: :delete,
                data: {confirm: t(".confirm_delete")},
                class: "btn btn-danger font-size-20" do %>
                <span class="glyphicon glyphicon-trash"></span>
              <% end %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>